app/moneyflow/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('transaction.urls')),


    # API
    path('api/v1/user/', include('user.api.user.urls')),
    path('api/v1/', include('transaction.api.transaction.urls')),

    # JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

app/transaction/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'transaction'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name="transaction:main", permanent=True)),
    path('main/', views.index, name='main'),
    path('create/', views.create_transaction, name='create'),
    path('create/', views.create_transaction, name='create'),
    path('update/<int:pk>', views.update_transaction, name='update'),
    path('delete/<int:pk>', views.delete_transaction, name='delete'),
    # Utils
    path('utils/', views.create_utils, name='utils'),
    path('utils/status/delete/<int:pk>/', views.delete_status, name='delete_status'),
    path('utils/type/delete/<int:pk>/', views.delete_transaction_type, name='delete_transaction_type'),
    path('utils/category/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('utils/subcategory/delete/<int:pk>/', views.delete_subcategory, name='delete_subcategory'),

    # ajax
    path('ajax/load-categories/', views.load_categories, name='ajax_load_categories'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
]

app/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('registration/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
]

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MoneyFlow{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    {% load static %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4">
        <a class="navbar-brand" href="{% url 'transaction:main' %}">MoneyFlow</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:profile' %}">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'transaction:utils' %}">Utils</a>
                    </li>
                    <li class="nav-item">
                        <form method="POST" action="{% url 'user:logout' %}">
                            {% csrf_token %}
                            <button class="nav-link" type="submit" >Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-K+ctZQ+YdBVzr+ZpjRPW5Sm3OqVJG0zO1Fz4RZ8F0hc="
        crossorigin="anonymous"></script>

</body>
</html>